---
- name: Ping hosts
  hosts: all
  become: yes
#  gather_facts: true

  tasks:
    - name: Test SSH
      wait_for_connection:
  
    - name: Gather facts
      gather_facts:
      register: fact_output

    - name: Debug register output
      debug:
        msg: "{{ fact_output }}"

